; Auto-generated. Do not edit!


(cl:in-package graph_navigation-msg)


;//! \htmlinclude graph_naviActionGoal.msg.html

(cl:defclass <graph_naviActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type graph_navigation-msg:graph_naviGoal
    :initform (cl:make-instance 'graph_navigation-msg:graph_naviGoal)))
)

(cl:defclass graph_naviActionGoal (<graph_naviActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <graph_naviActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'graph_naviActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graph_navigation-msg:<graph_naviActionGoal> is deprecated: use graph_navigation-msg:graph_naviActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <graph_naviActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graph_navigation-msg:header-val is deprecated.  Use graph_navigation-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <graph_naviActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graph_navigation-msg:goal_id-val is deprecated.  Use graph_navigation-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <graph_naviActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graph_navigation-msg:goal-val is deprecated.  Use graph_navigation-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <graph_naviActionGoal>) ostream)
  "Serializes a message object of type '<graph_naviActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <graph_naviActionGoal>) istream)
  "Deserializes a message object of type '<graph_naviActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<graph_naviActionGoal>)))
  "Returns string type for a message object of type '<graph_naviActionGoal>"
  "graph_navigation/graph_naviActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'graph_naviActionGoal)))
  "Returns string type for a message object of type 'graph_naviActionGoal"
  "graph_navigation/graph_naviActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<graph_naviActionGoal>)))
  "Returns md5sum for a message object of type '<graph_naviActionGoal>"
  "65e4c611c78cebc69ed2e2e2daa0cf73")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'graph_naviActionGoal)))
  "Returns md5sum for a message object of type 'graph_naviActionGoal"
  "65e4c611c78cebc69ed2e2e2daa0cf73")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<graph_naviActionGoal>)))
  "Returns full string definition for message of type '<graph_naviActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%graph_naviGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: graph_navigation/graph_naviGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 start~%int32 goal~%int32[] checkPoint~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'graph_naviActionGoal)))
  "Returns full string definition for message of type 'graph_naviActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%graph_naviGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: graph_navigation/graph_naviGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 start~%int32 goal~%int32[] checkPoint~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <graph_naviActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <graph_naviActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'graph_naviActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
