; Auto-generated. Do not edit!


(cl:in-package graph_navigation-msg)


;//! \htmlinclude graph_naviResult.msg.html

(cl:defclass <graph_naviResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass graph_naviResult (<graph_naviResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <graph_naviResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'graph_naviResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graph_navigation-msg:<graph_naviResult> is deprecated: use graph_navigation-msg:graph_naviResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <graph_naviResult>) ostream)
  "Serializes a message object of type '<graph_naviResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <graph_naviResult>) istream)
  "Deserializes a message object of type '<graph_naviResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<graph_naviResult>)))
  "Returns string type for a message object of type '<graph_naviResult>"
  "graph_navigation/graph_naviResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'graph_naviResult)))
  "Returns string type for a message object of type 'graph_naviResult"
  "graph_navigation/graph_naviResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<graph_naviResult>)))
  "Returns md5sum for a message object of type '<graph_naviResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'graph_naviResult)))
  "Returns md5sum for a message object of type 'graph_naviResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<graph_naviResult>)))
  "Returns full string definition for message of type '<graph_naviResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'graph_naviResult)))
  "Returns full string definition for message of type 'graph_naviResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <graph_naviResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <graph_naviResult>))
  "Converts a ROS message object to a list"
  (cl:list 'graph_naviResult
))
