; Auto-generated. Do not edit!


(cl:in-package graph_navigation-msg)


;//! \htmlinclude graph_naviFeedback.msg.html

(cl:defclass <graph_naviFeedback> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass graph_naviFeedback (<graph_naviFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <graph_naviFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'graph_naviFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graph_navigation-msg:<graph_naviFeedback> is deprecated: use graph_navigation-msg:graph_naviFeedback instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <graph_naviFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graph_navigation-msg:result-val is deprecated.  Use graph_navigation-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <graph_naviFeedback>) ostream)
  "Serializes a message object of type '<graph_naviFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <graph_naviFeedback>) istream)
  "Deserializes a message object of type '<graph_naviFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<graph_naviFeedback>)))
  "Returns string type for a message object of type '<graph_naviFeedback>"
  "graph_navigation/graph_naviFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'graph_naviFeedback)))
  "Returns string type for a message object of type 'graph_naviFeedback"
  "graph_navigation/graph_naviFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<graph_naviFeedback>)))
  "Returns md5sum for a message object of type '<graph_naviFeedback>"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'graph_naviFeedback)))
  "Returns md5sum for a message object of type 'graph_naviFeedback"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<graph_naviFeedback>)))
  "Returns full string definition for message of type '<graph_naviFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'graph_naviFeedback)))
  "Returns full string definition for message of type 'graph_naviFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <graph_naviFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <graph_naviFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'graph_naviFeedback
    (cl:cons ':result (result msg))
))
