// Generated by gencpp from file graph_navigation/graph_naviFeedback.msg
// DO NOT EDIT!


#ifndef GRAPH_NAVIGATION_MESSAGE_GRAPH_NAVIFEEDBACK_H
#define GRAPH_NAVIGATION_MESSAGE_GRAPH_NAVIFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_navigation
{
template <class ContainerAllocator>
struct graph_naviFeedback_
{
  typedef graph_naviFeedback_<ContainerAllocator> Type;

  graph_naviFeedback_()
    : result(0)  {
    }
  graph_naviFeedback_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct graph_naviFeedback_

typedef ::graph_navigation::graph_naviFeedback_<std::allocator<void> > graph_naviFeedback;

typedef boost::shared_ptr< ::graph_navigation::graph_naviFeedback > graph_naviFeedbackPtr;
typedef boost::shared_ptr< ::graph_navigation::graph_naviFeedback const> graph_naviFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_navigation::graph_naviFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graph_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'graph_navigation': ['/home/norihiro/dev_ws/devel/share/graph_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::graph_navigation::graph_naviFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_navigation/graph_naviFeedback";
  }

  static const char* value(const ::graph_navigation::graph_naviFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 result\n\
\n\
";
  }

  static const char* value(const ::graph_navigation::graph_naviFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct graph_naviFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_navigation::graph_naviFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_navigation::graph_naviFeedback_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_NAVIGATION_MESSAGE_GRAPH_NAVIFEEDBACK_H
