// Generated by gencpp from file graph_navigation/graph_naviResult.msg
// DO NOT EDIT!


#ifndef GRAPH_NAVIGATION_MESSAGE_GRAPH_NAVIRESULT_H
#define GRAPH_NAVIGATION_MESSAGE_GRAPH_NAVIRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_navigation
{
template <class ContainerAllocator>
struct graph_naviResult_
{
  typedef graph_naviResult_<ContainerAllocator> Type;

  graph_naviResult_()
    {
    }
  graph_naviResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::graph_navigation::graph_naviResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_navigation::graph_naviResult_<ContainerAllocator> const> ConstPtr;

}; // struct graph_naviResult_

typedef ::graph_navigation::graph_naviResult_<std::allocator<void> > graph_naviResult;

typedef boost::shared_ptr< ::graph_navigation::graph_naviResult > graph_naviResultPtr;
typedef boost::shared_ptr< ::graph_navigation::graph_naviResult const> graph_naviResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_navigation::graph_naviResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_navigation::graph_naviResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graph_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'graph_navigation': ['/home/norihiro/dev_ws/devel/share/graph_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graph_navigation::graph_naviResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_navigation::graph_naviResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_navigation::graph_naviResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_navigation::graph_naviResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_navigation::graph_naviResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_navigation::graph_naviResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_navigation::graph_naviResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::graph_navigation::graph_naviResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_navigation::graph_naviResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_navigation/graph_naviResult";
  }

  static const char* value(const ::graph_navigation::graph_naviResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_navigation::graph_naviResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
";
  }

  static const char* value(const ::graph_navigation::graph_naviResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_navigation::graph_naviResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct graph_naviResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_navigation::graph_naviResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::graph_navigation::graph_naviResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_NAVIGATION_MESSAGE_GRAPH_NAVIRESULT_H
