// Generated by gencpp from file graph_navigation/graph_naviGoal.msg
// DO NOT EDIT!


#ifndef GRAPH_NAVIGATION_MESSAGE_GRAPH_NAVIGOAL_H
#define GRAPH_NAVIGATION_MESSAGE_GRAPH_NAVIGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_navigation
{
template <class ContainerAllocator>
struct graph_naviGoal_
{
  typedef graph_naviGoal_<ContainerAllocator> Type;

  graph_naviGoal_()
    : start(0)
    , goal(0)
    , checkPoint()  {
    }
  graph_naviGoal_(const ContainerAllocator& _alloc)
    : start(0)
    , goal(0)
    , checkPoint(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _start_type;
  _start_type start;

   typedef int32_t _goal_type;
  _goal_type goal;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _checkPoint_type;
  _checkPoint_type checkPoint;





  typedef boost::shared_ptr< ::graph_navigation::graph_naviGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_navigation::graph_naviGoal_<ContainerAllocator> const> ConstPtr;

}; // struct graph_naviGoal_

typedef ::graph_navigation::graph_naviGoal_<std::allocator<void> > graph_naviGoal;

typedef boost::shared_ptr< ::graph_navigation::graph_naviGoal > graph_naviGoalPtr;
typedef boost::shared_ptr< ::graph_navigation::graph_naviGoal const> graph_naviGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_navigation::graph_naviGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_navigation::graph_naviGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graph_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'graph_navigation': ['/home/norihiro/dev_ws/devel/share/graph_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graph_navigation::graph_naviGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_navigation::graph_naviGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_navigation::graph_naviGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_navigation::graph_naviGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_navigation::graph_naviGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_navigation::graph_naviGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_navigation::graph_naviGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7adec3cf8709088ac0c64d29e882640";
  }

  static const char* value(const ::graph_navigation::graph_naviGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7adec3cf8709088ULL;
  static const uint64_t static_value2 = 0xac0c64d29e882640ULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_navigation::graph_naviGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_navigation/graph_naviGoal";
  }

  static const char* value(const ::graph_navigation::graph_naviGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_navigation::graph_naviGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 start\n\
int32 goal\n\
int32[] checkPoint\n\
";
  }

  static const char* value(const ::graph_navigation::graph_naviGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_navigation::graph_naviGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal);
      stream.next(m.checkPoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct graph_naviGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_navigation::graph_naviGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_navigation::graph_naviGoal_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<int32_t>::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal);
    s << indent << "checkPoint[]" << std::endl;
    for (size_t i = 0; i < v.checkPoint.size(); ++i)
    {
      s << indent << "  checkPoint[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.checkPoint[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_NAVIGATION_MESSAGE_GRAPH_NAVIGOAL_H
