// Generated by gencpp from file graph_server/GraphPathResponse.msg
// DO NOT EDIT!


#ifndef GRAPH_SERVER_MESSAGE_GRAPHPATHRESPONSE_H
#define GRAPH_SERVER_MESSAGE_GRAPHPATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_server
{
template <class ContainerAllocator>
struct GraphPathResponse_
{
  typedef GraphPathResponse_<ContainerAllocator> Type;

  GraphPathResponse_()
    : path()
    , lange(0.0)  {
    }
  GraphPathResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , lange(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _path_type;
  _path_type path;

   typedef float _lange_type;
  _lange_type lange;





  typedef boost::shared_ptr< ::graph_server::GraphPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_server::GraphPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GraphPathResponse_

typedef ::graph_server::GraphPathResponse_<std::allocator<void> > GraphPathResponse;

typedef boost::shared_ptr< ::graph_server::GraphPathResponse > GraphPathResponsePtr;
typedef boost::shared_ptr< ::graph_server::GraphPathResponse const> GraphPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_server::GraphPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_server::GraphPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graph_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graph_server::GraphPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_server::GraphPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_server::GraphPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_server::GraphPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_server::GraphPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_server::GraphPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_server::GraphPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9554f5687f705abdaaa928f25b9ba2f";
  }

  static const char* value(const ::graph_server::GraphPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9554f5687f705abULL;
  static const uint64_t static_value2 = 0xdaaa928f25b9ba2fULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_server::GraphPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_server/GraphPathResponse";
  }

  static const char* value(const ::graph_server::GraphPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_server::GraphPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64[] path\n\
float32 lange\n\
\n\
";
  }

  static const char* value(const ::graph_server::GraphPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_server::GraphPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.lange);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraphPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_server::GraphPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_server::GraphPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.path[i]);
    }
    s << indent << "lange: ";
    Printer<float>::stream(s, indent + "  ", v.lange);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_SERVER_MESSAGE_GRAPHPATHRESPONSE_H
