// Generated by gencpp from file graph_server/GraphPathRequest.msg
// DO NOT EDIT!


#ifndef GRAPH_SERVER_MESSAGE_GRAPHPATHREQUEST_H
#define GRAPH_SERVER_MESSAGE_GRAPHPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_server
{
template <class ContainerAllocator>
struct GraphPathRequest_
{
  typedef GraphPathRequest_<ContainerAllocator> Type;

  GraphPathRequest_()
    : start(0)
    , goal(0)  {
    }
  GraphPathRequest_(const ContainerAllocator& _alloc)
    : start(0)
    , goal(0)  {
  (void)_alloc;
    }



   typedef uint64_t _start_type;
  _start_type start;

   typedef uint64_t _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::graph_server::GraphPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_server::GraphPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GraphPathRequest_

typedef ::graph_server::GraphPathRequest_<std::allocator<void> > GraphPathRequest;

typedef boost::shared_ptr< ::graph_server::GraphPathRequest > GraphPathRequestPtr;
typedef boost::shared_ptr< ::graph_server::GraphPathRequest const> GraphPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_server::GraphPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_server::GraphPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graph_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graph_server::GraphPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_server::GraphPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_server::GraphPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_server::GraphPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_server::GraphPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_server::GraphPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_server::GraphPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dea57c8f4ba4a012d050a4c9e1f99ab9";
  }

  static const char* value(const ::graph_server::GraphPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdea57c8f4ba4a012ULL;
  static const uint64_t static_value2 = 0xd050a4c9e1f99ab9ULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_server::GraphPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_server/GraphPathRequest";
  }

  static const char* value(const ::graph_server::GraphPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_server::GraphPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 start\n\
uint64 goal\n\
";
  }

  static const char* value(const ::graph_server::GraphPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_server::GraphPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraphPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_server::GraphPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_server::GraphPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_SERVER_MESSAGE_GRAPHPATHREQUEST_H
