// Generated by gencpp from file graph_server/minial_pathResponse.msg
// DO NOT EDIT!


#ifndef GRAPH_SERVER_MESSAGE_MINIAL_PATHRESPONSE_H
#define GRAPH_SERVER_MESSAGE_MINIAL_PATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_server
{
template <class ContainerAllocator>
struct minial_pathResponse_
{
  typedef minial_pathResponse_<ContainerAllocator> Type;

  minial_pathResponse_()
    : path()
    , lange(0)  {
    }
  minial_pathResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , lange(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;

   typedef uint64_t _lange_type;
  _lange_type lange;





  typedef boost::shared_ptr< ::graph_server::minial_pathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_server::minial_pathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct minial_pathResponse_

typedef ::graph_server::minial_pathResponse_<std::allocator<void> > minial_pathResponse;

typedef boost::shared_ptr< ::graph_server::minial_pathResponse > minial_pathResponsePtr;
typedef boost::shared_ptr< ::graph_server::minial_pathResponse const> minial_pathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_server::minial_pathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_server::minial_pathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graph_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graph_server::minial_pathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_server::minial_pathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_server::minial_pathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_server::minial_pathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_server::minial_pathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_server::minial_pathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_server::minial_pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efbd5e318f3938791619ad5e81ecfba5";
  }

  static const char* value(const ::graph_server::minial_pathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefbd5e318f393879ULL;
  static const uint64_t static_value2 = 0x1619ad5e81ecfba5ULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_server::minial_pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_server/minial_pathResponse";
  }

  static const char* value(const ::graph_server::minial_pathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_server::minial_pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string path\n\
uint64 lange\n\
\n\
";
  }

  static const char* value(const ::graph_server::minial_pathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_server::minial_pathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.lange);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct minial_pathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_server::minial_pathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_server::minial_pathResponse_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
    s << indent << "lange: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.lange);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_SERVER_MESSAGE_MINIAL_PATHRESPONSE_H
