// Generated by gencpp from file graph_server/MinimalPath.msg
// DO NOT EDIT!


#ifndef GRAPH_SERVER_MESSAGE_MINIMALPATH_H
#define GRAPH_SERVER_MESSAGE_MINIMALPATH_H

#include <ros/service_traits.h>


#include <graph_server/MinimalPathRequest.h>
#include <graph_server/MinimalPathResponse.h>


namespace graph_server
{

struct MinimalPath
{

typedef MinimalPathRequest Request;
typedef MinimalPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MinimalPath
} // namespace graph_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graph_server::MinimalPath > {
  static const char* value()
  {
    return "6321f4afb0321f086bd12ec44b09a3b8";
  }

  static const char* value(const ::graph_server::MinimalPath&) { return value(); }
};

template<>
struct DataType< ::graph_server::MinimalPath > {
  static const char* value()
  {
    return "graph_server/MinimalPath";
  }

  static const char* value(const ::graph_server::MinimalPath&) { return value(); }
};


// service_traits::MD5Sum< ::graph_server::MinimalPathRequest> should match 
// service_traits::MD5Sum< ::graph_server::MinimalPath > 
template<>
struct MD5Sum< ::graph_server::MinimalPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graph_server::MinimalPath >::value();
  }
  static const char* value(const ::graph_server::MinimalPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_server::MinimalPathRequest> should match 
// service_traits::DataType< ::graph_server::MinimalPath > 
template<>
struct DataType< ::graph_server::MinimalPathRequest>
{
  static const char* value()
  {
    return DataType< ::graph_server::MinimalPath >::value();
  }
  static const char* value(const ::graph_server::MinimalPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graph_server::MinimalPathResponse> should match 
// service_traits::MD5Sum< ::graph_server::MinimalPath > 
template<>
struct MD5Sum< ::graph_server::MinimalPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graph_server::MinimalPath >::value();
  }
  static const char* value(const ::graph_server::MinimalPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_server::MinimalPathResponse> should match 
// service_traits::DataType< ::graph_server::MinimalPath > 
template<>
struct DataType< ::graph_server::MinimalPathResponse>
{
  static const char* value()
  {
    return DataType< ::graph_server::MinimalPath >::value();
  }
  static const char* value(const ::graph_server::MinimalPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRAPH_SERVER_MESSAGE_MINIMALPATH_H
