// Generated by gencpp from file graph_server/minial_path.msg
// DO NOT EDIT!


#ifndef GRAPH_SERVER_MESSAGE_MINIAL_PATH_H
#define GRAPH_SERVER_MESSAGE_MINIAL_PATH_H

#include <ros/service_traits.h>


#include <graph_server/minial_pathRequest.h>
#include <graph_server/minial_pathResponse.h>


namespace graph_server
{

struct minial_path
{

typedef minial_pathRequest Request;
typedef minial_pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct minial_path
} // namespace graph_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graph_server::minial_path > {
  static const char* value()
  {
    return "877cb00e6b709c3bf4e2cda35c97bf9e";
  }

  static const char* value(const ::graph_server::minial_path&) { return value(); }
};

template<>
struct DataType< ::graph_server::minial_path > {
  static const char* value()
  {
    return "graph_server/minial_path";
  }

  static const char* value(const ::graph_server::minial_path&) { return value(); }
};


// service_traits::MD5Sum< ::graph_server::minial_pathRequest> should match 
// service_traits::MD5Sum< ::graph_server::minial_path > 
template<>
struct MD5Sum< ::graph_server::minial_pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graph_server::minial_path >::value();
  }
  static const char* value(const ::graph_server::minial_pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_server::minial_pathRequest> should match 
// service_traits::DataType< ::graph_server::minial_path > 
template<>
struct DataType< ::graph_server::minial_pathRequest>
{
  static const char* value()
  {
    return DataType< ::graph_server::minial_path >::value();
  }
  static const char* value(const ::graph_server::minial_pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graph_server::minial_pathResponse> should match 
// service_traits::MD5Sum< ::graph_server::minial_path > 
template<>
struct MD5Sum< ::graph_server::minial_pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graph_server::minial_path >::value();
  }
  static const char* value(const ::graph_server::minial_pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_server::minial_pathResponse> should match 
// service_traits::DataType< ::graph_server::minial_path > 
template<>
struct DataType< ::graph_server::minial_pathResponse>
{
  static const char* value()
  {
    return DataType< ::graph_server::minial_path >::value();
  }
  static const char* value(const ::graph_server::minial_pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRAPH_SERVER_MESSAGE_MINIAL_PATH_H
