// Generated by gencpp from file graph_server/minial_pathRequest.msg
// DO NOT EDIT!


#ifndef GRAPH_SERVER_MESSAGE_MINIAL_PATHREQUEST_H
#define GRAPH_SERVER_MESSAGE_MINIAL_PATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_server
{
template <class ContainerAllocator>
struct minial_pathRequest_
{
  typedef minial_pathRequest_<ContainerAllocator> Type;

  minial_pathRequest_()
    : start()
    , goal()  {
    }
  minial_pathRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _start_type;
  _start_type start;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::graph_server::minial_pathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_server::minial_pathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct minial_pathRequest_

typedef ::graph_server::minial_pathRequest_<std::allocator<void> > minial_pathRequest;

typedef boost::shared_ptr< ::graph_server::minial_pathRequest > minial_pathRequestPtr;
typedef boost::shared_ptr< ::graph_server::minial_pathRequest const> minial_pathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_server::minial_pathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_server::minial_pathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graph_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graph_server::minial_pathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_server::minial_pathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_server::minial_pathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_server::minial_pathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_server::minial_pathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_server::minial_pathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_server::minial_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db3d2f7e614f0d3b76c6b211062636db";
  }

  static const char* value(const ::graph_server::minial_pathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb3d2f7e614f0d3bULL;
  static const uint64_t static_value2 = 0x76c6b211062636dbULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_server::minial_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_server/minial_pathRequest";
  }

  static const char* value(const ::graph_server::minial_pathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_server::minial_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string start\n\
string goal\n\
";
  }

  static const char* value(const ::graph_server::minial_pathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_server::minial_pathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct minial_pathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_server::minial_pathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_server::minial_pathRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_SERVER_MESSAGE_MINIAL_PATHREQUEST_H
