// Generated by gencpp from file graph_server/NodeInfo.msg
// DO NOT EDIT!


#ifndef GRAPH_SERVER_MESSAGE_NODEINFO_H
#define GRAPH_SERVER_MESSAGE_NODEINFO_H

#include <ros/service_traits.h>


#include <graph_server/NodeInfoRequest.h>
#include <graph_server/NodeInfoResponse.h>


namespace graph_server
{

struct NodeInfo
{

typedef NodeInfoRequest Request;
typedef NodeInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NodeInfo
} // namespace graph_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graph_server::NodeInfo > {
  static const char* value()
  {
    return "2029851a1bf8e47ba40fa92c11e0df36";
  }

  static const char* value(const ::graph_server::NodeInfo&) { return value(); }
};

template<>
struct DataType< ::graph_server::NodeInfo > {
  static const char* value()
  {
    return "graph_server/NodeInfo";
  }

  static const char* value(const ::graph_server::NodeInfo&) { return value(); }
};


// service_traits::MD5Sum< ::graph_server::NodeInfoRequest> should match 
// service_traits::MD5Sum< ::graph_server::NodeInfo > 
template<>
struct MD5Sum< ::graph_server::NodeInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graph_server::NodeInfo >::value();
  }
  static const char* value(const ::graph_server::NodeInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_server::NodeInfoRequest> should match 
// service_traits::DataType< ::graph_server::NodeInfo > 
template<>
struct DataType< ::graph_server::NodeInfoRequest>
{
  static const char* value()
  {
    return DataType< ::graph_server::NodeInfo >::value();
  }
  static const char* value(const ::graph_server::NodeInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graph_server::NodeInfoResponse> should match 
// service_traits::MD5Sum< ::graph_server::NodeInfo > 
template<>
struct MD5Sum< ::graph_server::NodeInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graph_server::NodeInfo >::value();
  }
  static const char* value(const ::graph_server::NodeInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_server::NodeInfoResponse> should match 
// service_traits::DataType< ::graph_server::NodeInfo > 
template<>
struct DataType< ::graph_server::NodeInfoResponse>
{
  static const char* value()
  {
    return DataType< ::graph_server::NodeInfo >::value();
  }
  static const char* value(const ::graph_server::NodeInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRAPH_SERVER_MESSAGE_NODEINFO_H
